### ISSUE TITLE
Nothing happens when clicking on a drug on drug landing pages

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/covid19_crowd_library#97] opened 2020-04-11 19:41 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maxim-k** [comment] 2020-04-12 15:38
Duplicate of #75

**Closed by maxim-k** 2020-04-12 15:38 UTC
