### ISSUE TITLE
Redundant Issue: No success message upon clicking Submit button

### ISSUE THREAD

**Issue by KMJ1618** [MaayanLab/covid19_crowd_library#38] opened 2020-03-28 20:50 UTC
Update 3/29/20: This issue can be marked as resolved, since it's redundant with issues #16 and #30.

I'm attempting to submit the entry below; I'm providing complete content so that you can try to reproduce this example yourself. Using either Chrome or Firefox browsers, after I enter the following content into the respective fields, nothing happens when I click the Submit button. I have waited up to ~2 minutes to see if a progress message is just missing, but I'm not detecting any activity from my clicking the Submit button...

Checking or unchecking the "Share contact information" checkbox doesn't appear to affect behavior.

Gene Set Name: SARS 133 Literature-Associated Genes from Geneshot GeneRIF

How this set is related to COVID-19 research? SARS (severe acute respiratory syndrome) is caused by coronavirus, and the term SARS is a component of the name of COVID-19 (SARS-CoV-2) as well as referring to earlier historical and related SARS-CoV viruses.

Gene List:
ACE2
TMPRSS2
MBL2
CD209
MX1
CXCL10
TNF
CLEC4M
IFNB1
CCL2
IFNG
IRF3
IL6
NFKB1
ACE
HLA-A
STAT1
CCL5
FGL2
IL10
HLA-DRB1
ADAM17
HLA-B
CTNNB1
PLA2G2D
OAS1
FCER2
TMPRSS11D
POU5F1
TMEM173
CASP3
CTSL
IFNA1
BCL2L1
UBE2I
DPP4
CLEC4G
PPIA
MASP2
SARS
HLA-C
TICAM2
CCND3
HOXA9
ICAM3
IFITM1
RB1
PF4
IL17A
PTX3
NPIPB3
FCGR2A
PSMC6
KLF6
WARS2
MAPK14
MPP5
NOS3
PKLR
MAPK3
IFNL3
IL12RB1
VHL
STAT6
MAPK1
EGFR
RELA
RCHY1
TLR4
CANX
IL1B
IL1A
F5
F2
SFTPD
DDX58
AHSG
ANXA2
CD34
TSPO
BDKRB1
CASP6
MAP1LC3A
ESM1
CXCL5
CXCL2
GPT
HSPB1
CXCL9
MYD88
PI4KB
IL4
IL2
EIF2S1
PPBP
NMI
ISG15
EIF2AK2
APOBEC3G
GOT1
SMAD3
EGR1
HLA-DQA2
CD14
HMOX1
THPO
CLTRN
UBB
CFP
PHB
DDX1
DDX5
VCP
IFNAR1
KPNB1
TP53
ATF6
EZR
EEF1A1
RUNX1
ZCRB1
KPNA2
IL12B
TRIM25
TBK1
CXCL16
PHB2
NUDT2
SERPINE1
CSF2
SPI1
C11ORF74
IFITM3

Name: ...
Affiliation: ...
E-mail: ...

**Comment by AviMaayan** [comment] 2020-03-28 22:29
@KMJ1618 I saw that you submitted this list 7 times... I accepted 1 and rejected the rest. So although there is no feedback, when you press submit the list is registered. So you can continue submitting lists if you find time.

**Comment by KMJ1618** [comment] 2020-03-29 03:19
Ok -- I see that my submission has been registered. Thanks for the update; I'll plan to continue submitting lists.

**Comment by maxim-k** [comment] 2020-03-30 16:09
Closing as a duplicate of #12

**Closed by maxim-k** 2020-03-30 16:09 UTC
